version: '3'

services:
  frontend:
    build: ./flaskfrontend
    ports:
      - '3000:3000'
    volumes:      
      - /app/node_modules
      - ./flaskfrontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      

  api: 
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
    depends_on:
      - mongo

volumes:
  mongodb_data: